### ISSUE TITLE
Not as advertised

### ISSUE THREAD

**Issue by Meekohi** [Zalastax/no-one-left-behind#8]
https://github.com/Zalastax/no-one-left-behind/blob/fa8467edaece8bced43a213e161d02bbba743877/update-package.js#L71-L73

https://github.com/Zalastax/no-one-left-behind/blob/fa8467edaece8bced43a213e161d02bbba743877/update-package.js#L86

You should feel ashamed.

**Comment by lamebear** [comment]
This can be fixed by grouping 1000 dependencies into a group package. Then, we create aggregation packages that depend on up to 100 groups, making those aggregation packages dependencies of this package. Doing that, we should be able to include all 1.3+ million packages as dependencies, if not directly.

```
no-one-left-behind
  no-one-left-behind-agg-1
    no-one-left-behind-group-1
      {regular packages}
    no-one-left-behind-group-2
      {regular packages}
    ...
    no-one-left-behind-group-1000
      {regular packages}
  no-one-left-behind-agg-2
    no-one-left-behind-group-1001
      {regular packages}
    no-one-left-behind-group-1002
      {regular packages}
```

**Comment by edgarsi** [comment]
Still not fixed :(
